import type { TableConfig } from "./field-types";

// Display/edit configuration for every property knowledge table.
// The generic list and edit pages under app/(admin)/knowledge read from this.
//
// New tables: add a TableConfig entry here and a Drizzle table to
// lib/db/schema/. The generic pages pick them up automatically.

const CENTS_RENDER = (v: unknown) =>
  typeof v === "number" ? `$${(v / 100).toFixed(2)}` : "—";

export const KNOWLEDGE_TABLE_CONFIGS: TableConfig[] = [
  {
    slug: "property-profile",
    label: "Property profile",
    tableName: "property_profile",
    isSingleton: true,
    description:
      "Top-level facts about the property. Used as identity in every generated marketing piece.",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "nickname", label: "Nickname", type: "text", required: true },
      { name: "address", label: "Address", type: "text", required: true },
      { name: "phone", label: "Phone", type: "text", required: true },
      { name: "email", label: "Email", type: "text", required: true },
      { name: "brandCollection", label: "Brand collection", type: "text" },
      { name: "totalRooms", label: "Total rooms", type: "number", required: true,
        help: "Must equal SUM(room_types.count). Enforced by DB trigger." },
      { name: "style", label: "Style", type: "text", required: true },
      { name: "setting", label: "Setting", type: "text", required: true },
      { name: "distanceSydneyCbdMin", label: "Distance to Sydney CBD (min)", type: "number" },
      { name: "distanceNewcastleMin", label: "Distance to Newcastle (min)", type: "number" },
      { name: "tagline", label: "Tagline", type: "text" },
      { name: "website", label: "Website", type: "text" },
      { name: "instagram", label: "Instagram", type: "text" },
      { name: "facebook", label: "Facebook", type: "text" },
      { name: "bookingEngineInternal", label: "Booking engine", type: "text" },
      { name: "eventBookingSystem", label: "Event booking system", type: "text" },
      { name: "restaurantBookingSystem", label: "Restaurant booking system", type: "text" },
      { name: "pms", label: "PMS", type: "text" },
    ],
  },
  {
    slug: "room-types",
    label: "Room types",
    tableName: "room_types",
    isSingleton: false,
    description:
      "One row per accommodation type. Sum of count must equal property_profile.total_rooms.",
    listColumns: [
      { field: "name", label: "Name" },
      { field: "tier", label: "Tier" },
      { field: "count", label: "Count" },
      { field: "maxGuests", label: "Max guests" },
      { field: "standardMidweekRateLow", label: "Rate low", render: CENTS_RENDER },
      { field: "standardMidweekRateHigh", label: "Rate high", render: CENTS_RENDER },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "beds", label: "Beds", type: "text", required: true,
        help: 'e.g. "1 king OR 2 queens"' },
      { name: "maxGuests", label: "Max guests", type: "number", required: true },
      { name: "tier", label: "Tier", type: "select", required: true,
        options: [
          { value: "Premium", label: "Premium" },
          { value: "Mid", label: "Mid" },
          { value: "Lower", label: "Lower" },
          { value: "Entry", label: "Entry" },
          { value: "Value", label: "Value" },
        ] },
      { name: "view", label: "View", type: "text" },
      { name: "notableFeatures", label: "Notable features", type: "textarea", wide: true },
      { name: "retireeSuitabilityNotes", label: "Retiree-suitability notes",
        type: "textarea", wide: true,
        help: "How well this room serves retirees. Influences package generation." },
      { name: "count", label: "Count (rooms of this type)", type: "number", required: true,
        help: "Sum across all room types must equal property_profile.total_rooms (83)." },
      { name: "standardMidweekRateLow", label: "Standard midweek rate — low ($)",
        type: "money_cents",
        help: "Drives P&L calculations in package proposals." },
      { name: "standardMidweekRateHigh", label: "Standard midweek rate — high ($)",
        type: "money_cents" },
      { name: "isAccessible", label: "Wheelchair accessible", type: "boolean",
        help: "Only true rooms may be described as accessible. See PLAN.md §9." },
      { name: "mobilityFriendlyCount", label: "Mobility-friendly count", type: "number",
        help: "Rooms ground-floor / walk-in shower / close to lifts. Described using the approved phrase only." },
    ],
  },
  {
    slug: "function-spaces",
    label: "Function spaces",
    tableName: "function_spaces",
    isSingleton: false,
    listColumns: [
      { field: "name", label: "Name" },
      { field: "capacityCocktail", label: "Cocktail" },
      { field: "capacityBanquet", label: "Banquet" },
      { field: "capacityTheatre", label: "Theatre" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "style", label: "Style", type: "textarea", wide: true },
      { name: "views", label: "Views", type: "text" },
      { name: "capacityCocktail", label: "Capacity — cocktail", type: "number" },
      { name: "capacityBanquet", label: "Capacity — banquet", type: "number" },
      { name: "capacityTheatre", label: "Capacity — theatre", type: "number" },
      { name: "bestFor", label: "Best for", type: "textarea", wide: true },
    ],
  },
  {
    slug: "fb-venues",
    label: "F&B venues",
    tableName: "fb_venues",
    isSingleton: false,
    listColumns: [
      { field: "name", label: "Name" },
      { field: "type", label: "Type" },
      { field: "capacity", label: "Capacity" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "type", label: "Type", type: "text", required: true },
      { name: "style", label: "Style", type: "text" },
      { name: "capacity", label: "Capacity", type: "number" },
      { name: "notes", label: "Notes", type: "textarea", wide: true },
      { name: "costPerHeadBreakfastCents", label: "Cost per head — breakfast ($)", type: "money_cents" },
      { name: "costPerHeadLunchCents", label: "Cost per head — lunch ($)", type: "money_cents" },
      { name: "costPerHeadDinner2cCents", label: "Cost per head — 2-course dinner ($)", type: "money_cents" },
      { name: "costPerHeadDinner3cCents", label: "Cost per head — 3-course dinner ($)", type: "money_cents" },
      { name: "costPerHeadCanapesCents", label: "Cost per head — canapés ($)", type: "money_cents" },
      { name: "beveragePackageOptions", label: "Beverage package options (JSON)", type: "json", wide: true,
        help: 'JSON object mapping package id to price in cents. e.g. {"2hr_house": 3500}' },
    ],
  },
  {
    slug: "regular-programming",
    label: "Regular programming",
    tableName: "regular_programming",
    isSingleton: false,
    description:
      "Recurring weekly/monthly events the system must work around when proposing midweek events.",
    listColumns: [
      { field: "event", label: "Event" },
      { field: "frequency", label: "Frequency" },
      { field: "dayOfWeek", label: "Day" },
      { field: "time", label: "Time" },
      { field: "venue", label: "Venue" },
    ],
    fields: [
      { name: "event", label: "Event name", type: "text", required: true },
      { name: "frequency", label: "Frequency", type: "select", required: true,
        options: [
          { value: "weekly", label: "Weekly" },
          { value: "fortnightly", label: "Fortnightly" },
          { value: "monthly", label: "Monthly" },
          { value: "annual", label: "Annual" },
        ] },
      { name: "dayOfWeek", label: "Day of week", type: "select",
        options: [
          { value: "", label: "—" },
          { value: "Monday", label: "Monday" },
          { value: "Tuesday", label: "Tuesday" },
          { value: "Wednesday", label: "Wednesday" },
          { value: "Thursday", label: "Thursday" },
          { value: "Friday", label: "Friday" },
          { value: "Saturday", label: "Saturday" },
          { value: "Sunday", label: "Sunday" },
        ] },
      { name: "time", label: "Time (HH:MM)", type: "time" },
      { name: "venue", label: "Venue", type: "text" },
      { name: "impactNotes", label: "Impact on midweek events", type: "textarea", wide: true },
    ],
  },
  {
    slug: "local-pois",
    label: "Local points of interest",
    tableName: "local_context_pois",
    isSingleton: false,
    listColumns: [
      { field: "name", label: "Name" },
      { field: "distanceMin", label: "Distance (min)" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "distanceMin", label: "Distance (driving minutes)", type: "number" },
      { name: "notes", label: "Notes", type: "textarea", wide: true },
    ],
  },
  {
    slug: "target-postcodes",
    label: "Target postcodes",
    tableName: "target_postcodes",
    isSingleton: false,
    description:
      "Postcodes the system targets in paid ads and partner-distribution recommendations.",
    listColumns: [
      { field: "postcode", label: "Postcode" },
      { field: "region", label: "Region" },
      { field: "suburbs", label: "Suburbs" },
      { field: "driveTimeMin", label: "Drive time" },
    ],
    fields: [
      { name: "postcode", label: "Postcode", type: "text", required: true },
      { name: "region", label: "Region", type: "select", required: true,
        options: [
          { value: "western_sydney", label: "Western Sydney" },
          { value: "north_shore", label: "Sydney North Shore" },
          { value: "newcastle_lake_macquarie", label: "Newcastle / Lake Macquarie" },
          { value: "central_coast", label: "Central Coast" },
          { value: "other", label: "Other" },
        ] },
      { name: "suburbs", label: "Suburbs", type: "text" },
      { name: "driveTimeMin", label: "Drive time (minutes)", type: "number" },
      { name: "retireeDensity", label: "Retiree density", type: "text",
        help: "Free-form notes — e.g. 'High, affluent'" },
    ],
  },
  {
    slug: "brand-voice",
    label: "Brand voice",
    tableName: "brand_voice",
    isSingleton: true,
    description:
      "Voice guide injected into every generation. Must be reviewed by manager (§10 hard gate) before any asset generation runs.",
    fields: [
      { name: "guideMarkdown", label: "Voice guide (Markdown)", type: "textarea", wide: true,
        required: true,
        help: "Written voice description. Edit freely." },
      { name: "rules", label: "Rules (JSON)", type: "json", wide: true,
        help: 'Structured rules. e.g. {"anchors": ["Hamptons-inspired"], "lightly_cheeky_aussie": true}' },
      { name: "forbiddenPhrases", label: "Forbidden phrases", type: "tags",
        help: "Comma-separated. Generation rejects any output containing these." },
      { name: "requiredPhrasesPerContext", label: "Required phrases per context (JSON)",
        type: "json", wide: true,
        help: 'JSON mapping context to required phrase. e.g. {"rsa": "Please drink responsibly."}' },
      { name: "reviewedByManager", label: "Reviewed and approved by manager", type: "boolean",
        help: "Manager hard gate. Generation refuses until this is true." },
    ],
  },
  {
    slug: "operational-constants",
    label: "Operational constants",
    tableName: "operational_constants",
    isSingleton: true,
    description: "Cross-cutting constants used in pricing, accessibility, and brand compliance.",
    fields: [
      { name: "blackoutDates", label: "Blackout dates (JSON array of YYYY-MM-DD)",
        type: "json", wide: true,
        help: 'e.g. ["2026-04-25"] — system refuses to propose events on these dates.' },
      { name: "rateFloorsCents", label: "Rate floors per room type (JSON)", type: "json", wide: true },
      { name: "rateCeilingsCents", label: "Rate ceilings per room type (JSON)", type: "json", wide: true },
      { name: "accessibilityNotes", label: "Accessibility notes", type: "textarea", wide: true },
      { name: "mobilityFriendlyApprovedPhrase", label: "Approved phrase for mobility-friendly rooms",
        type: "text",
        help: "The ONLY phrase generation may use for mobility-friendly rooms. See PLAN.md §9." },
      { name: "choiceHotelsBrandNotes", label: "Choice Hotels / Ascend brand notes",
        type: "textarea", wide: true },
      { name: "brandVoiceScoreThreshold", label: "Brand voice score threshold (0–100)", type: "number",
        help: "Assets scoring below this auto-regenerate once. Default 70." },
    ],
  },
  {
    slug: "photo-library",
    label: "Photo library",
    tableName: "photo_library",
    isSingleton: false,
    description:
      "All hotel / room / lake / food photography. Hard gate: ≥40 photos required before asset generation runs.",
    listColumns: [
      { field: "category", label: "Category" },
      { field: "altText", label: "Alt text" },
      { field: "storagePath", label: "Storage path" },
    ],
    fields: [
      { name: "storagePath", label: "Storage path", type: "text", required: true,
        help: "Path in Supabase Storage. Real upload UI lands in feat/asset-images-category; for now, paste a path." },
      { name: "category", label: "Category", type: "select", required: true,
        options: [
          { value: "exterior", label: "Exterior" },
          { value: "rooms", label: "Rooms" },
          { value: "lake", label: "Lake / waterfront" },
          { value: "grounds", label: "Grounds / pool" },
          { value: "food", label: "Food" },
          { value: "function_spaces", label: "Function spaces" },
          { value: "lifestyle", label: "Lifestyle" },
          { value: "brand_detail", label: "Brand detail" },
        ] },
      { name: "altText", label: "Alt text", type: "text", required: true },
      { name: "tags", label: "Tags", type: "tags" },
    ],
  },
  {
    slug: "talent-database",
    label: "Talent database",
    tableName: "talent_database",
    isSingleton: false,
    description:
      "Third-party talent (musicians, instructors, artists). Used by event invention to source shortlists.",
    listColumns: [
      { field: "name", label: "Name" },
      { field: "type", label: "Type" },
      { field: "feeRangeLowCents", label: "Fee low", render: CENTS_RENDER },
      { field: "feeRangeHighCents", label: "Fee high", render: CENTS_RENDER },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "type", label: "Type", type: "text", required: true,
        help: "e.g. 'Watercolour instructor', 'Jazz trio'" },
      { name: "contact", label: "Contact", type: "text" },
      { name: "feeRangeLowCents", label: "Fee range — low ($)", type: "money_cents" },
      { name: "feeRangeHighCents", label: "Fee range — high ($)", type: "money_cents" },
      { name: "notes", label: "Notes", type: "textarea", wide: true },
    ],
  },
];

export function getTableConfig(slug: string): TableConfig | undefined {
  return KNOWLEDGE_TABLE_CONFIGS.find((t) => t.slug === slug);
}
